const viewMore = document.getElementById("view-more")
const date  =    document.getElementById("date")
const mainText =     document.getElementById("main-text")
const paraText =     document.getElementById("para-text")
const aboutMe = document.querySelector(".about-me")
const home = document.querySelector(".home")

viewMore.addEventListener("click",()=>{
    document.getElementById("img-background").classList.add("upper-space")
    date.classList.add("go-up-date")
    mainText.classList.add("go-up-main-text")
    paraText.classList.add("go-up-para-text")
    date.classList.remove("date-media")
    mainText.classList.remove("main-text-media")
    paraText.classList.remove("para-text-media")
    document.getElementById("para").classList.add("display")
    document.getElementById("profile").classList.remove("display")
    document.getElementById("img-background").classList.add("display")
    scrollTo(top)
})

aboutMe.addEventListener("click",()=>{
    document.getElementById("profile").classList.add("display")
    document.querySelector(".img-background").classList.remove("display")
    document.querySelector(".img-background").classList.add("disable")
    document.getElementById("para").classList.add("display") 
    scrollTo(top)

})
home.addEventListener("click",()=>{
    document.getElementById("img-background").classList.remove("upper-space")
    document.getElementById("img-background").classList.add("display")
    document.getElementById("profile").classList.remove("display")
    document.getElementById("para").classList.remove("display")
    date.classList.remove("go-up-date")
    mainText.classList.remove("go-up-main-text")
    paraText.classList.remove("go-up-para-text")
    date.classList.add("date-media")
    mainText.classList.add("main-text-media")
    paraText.classList.add("para-text-media")
})